version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: ./web_api/ECommerce.API
    ports:
      - "7149:80"
  client:
    build: ./client
    volumes:
      - ./client:/opt/app
    ports:
      - 5010:5010
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sql_server2022
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=A&VeryComplex123Password